google_search_task:
  description: >
    Conduct a thorough search of news articles for this topic: {topic}
    Make sure you find any interesting and relevant information until the current year {date}.
  expected_output: >
    The list of 10 websites with the most relevant information about this topic: {topic}
  agent: google_search

news_scraper_task:
  description: >
    Scrape the website for the latest news and information
  expected_output: >
    Fully scraped websites with all the important information from the website.
  agent: news_scraper
  
news_summariser_task:
  description: >
    Write the news article to a file
  expected_output: >
    I need you to generate a summary to the entire scraped information to only 2 paragraphs. The summary should be properly formatted as markdown without '```'
  agent: news_summariser
  
save_news_articles_task:
  description: >
    Write the news article to a file
  expected_output: >
    A fully fledge news article with all information from previous task into a file named {file_name}.md
  agent: save_news_articles

  
